# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and distribute to Firebase App Distribution"
  lane :beta do
    gradle(
      task: "assemble",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      testers: "prshuvo1971@gmail.com",
      release_notes: "Build from CI pipeline",
      android_artifact_type: "APK", # or "AAB"
      apk_path: "app/build/outputs/apk/release/app-release.apk"
    )
  end
end
